blank_issues_enabled: false
contact_links:
  - name: 💬 Zetian Discussions
    url: https://github.com/Taiizor/Zetian/discussions
    about: Ask questions, share ideas, and discuss Zetian features
  - name: 📚 Zetian Documentation
    url: https://zetian.soferity.com
    about: Comprehensive guides, API reference, and tutorials
  - name: 🔒 Security Issues
    url: mailto:taiizor@vegalya.com
    about: Report critical security vulnerabilities privately
  - name: 💡 Stack Overflow
    url: https://stackoverflow.com/questions/tagged/zetian
    about: Get help from the community for technical questions
  - name: 📦 NuGet Package
    url: https://www.nuget.org/packages/Zetian
    about: View package details and download statistics
  - name: 💼 Commercial Support
    url: mailto:taiizor@vegalya.com
    about: Get professional support and consulting services