name: Documentation Improvement
description: Suggest improvements to Zetian documentation
title: "[Docs]: "
labels: ["documentation", "good first issue"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! Please fill out the sections below.
        
        📚 **Documentation Site**: https://zetian.soferity.com
  
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - API Reference
        - Getting Started Guide
        - Configuration Examples
        - Authentication Guide
        - Performance Tuning
        - Security Best Practices
        - Migration Guide
        - Code Examples
        - Website/Documentation Site
        - Changelog
        - README
        - Other
    validations:
      required: true
  
  - type: input
    id: location
    attributes:
      label: Current Documentation Location
      description: Where is the current documentation located? (URL, file path, or section name)
      placeholder: |
        Examples:
        - https://zetian.soferity.com/docs
        - https://zetian.soferity.com/examples
        - https://zetian.soferity.com/changelog
        - README.md section
        - /.pages/app/docs/...
    validations:
      required: false
  
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong or missing in the current documentation?
      placeholder: |
        The documentation for X is unclear because...
        There's no example showing how to...
        The section about Y is outdated...
        The website navigation could be improved...
    validations:
      required: true
  
  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Add a section explaining...
        Include code examples for...
        Clarify the description of...
        Add interactive examples to the website...
        Improve search functionality...
    validations:
      required: true
  
  - type: textarea
    id: example-content
    attributes:
      label: Proposed Content (if applicable)
      description: If you have specific text or code examples, please provide them here
      placeholder: |
        ## Example Section
        
        Here's how to configure authentication:
        
        ```csharp
        var authConfig = new AuthenticationConfig
        {
            // Configuration details
        };
        ```
      render: markdown
    validations:
      required: false
  
  - type: checkboxes
    id: affected-areas
    attributes:
      label: Affected Areas
      description: Which areas of the library does this documentation cover?
      options:
        - label: SMTP Server Configuration
        - label: Authentication & Security
        - label: Message Processing
        - label: Rate Limiting
        - label: Extension Support
        - label: Error Handling
        - label: Performance & Scaling
        - label: Testing & Debugging
        - label: Website UI/UX
        - label: API Documentation
        - label: Code Examples
  
  - type: dropdown
    id: user-level
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - Beginners - New to SMTP or Zetian
        - Intermediate - Familiar with basics
        - Advanced - Expert users
        - All levels
    validations:
      required: true
  
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help with this improvement?
      options:
        - label: I can provide the documentation content
        - label: I can review the changes
        - label: I can provide code examples
        - label: I can translate to other languages
  
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any other information that might be helpful
      placeholder: "Related issues, similar documentation in other projects, etc."
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Taiizor/Zetian/blob/develop/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true