name: Performance Issue
description: Report performance problems or bottlenecks in Zetian
title: "[Performance]: "
labels: ["performance", "optimization"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Help us improve Zetian's performance by reporting bottlenecks or inefficiencies.
  
  - type: dropdown
    id: issue-type
    attributes:
      label: Performance Issue Type
      description: What kind of performance issue are you experiencing?
      options:
        - High CPU Usage
        - High Memory Usage
        - Memory Leaks
        - Slow Message Processing
        - Connection Handling Issues
        - Throughput Limitations
        - Response Time Degradation
        - Resource Exhaustion
        - Scalability Issues
        - Other
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the performance problem you're experiencing
      placeholder: |
        The server slows down when...
        Memory usage increases continuously when...
        CPU spikes to 100% when...
    validations:
      required: true
  
  - type: textarea
    id: expected-performance
    attributes:
      label: Expected Performance
      description: What performance levels were you expecting?
      placeholder: |
        Should handle 1000 messages/second...
        Memory usage should stay under 500MB...
    validations:
      required: true
  
  - type: textarea
    id: actual-performance
    attributes:
      label: Actual Performance
      description: What performance are you actually seeing?
      placeholder: |
        Only handles 100 messages/second...
        Memory usage grows to 2GB...
    validations:
      required: true
  
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Share your Zetian configuration (sanitize sensitive data)
      placeholder: |
        ```csharp
        var config = new SmtpServerConfiguration
        {
            MaxConnections = 100,
            // Other settings...
        };
        ```
      render: csharp
    validations:
      required: false
  
  - type: textarea
    id: metrics
    attributes:
      label: Performance Metrics
      description: Provide any performance metrics you've collected
      placeholder: |
        - Messages per second: X
        - Average response time: Y ms
        - Memory usage: Z MB
        - CPU usage: N%
        - Connection count: C
    validations:
      required: false
  
  - type: textarea
    id: profiling
    attributes:
      label: Profiling Data (if available)
      description: Share any profiling results or performance traces
      placeholder: |
        Attach profiler output, flame graphs, or performance traces
    validations:
      required: false
  
  - type: input
    id: load-characteristics
    attributes:
      label: Load Characteristics
      description: Describe your typical load pattern
      placeholder: "100 concurrent connections, 500 msgs/sec average"
    validations:
      required: false
  
  - type: dropdown
    id: environment-type
    attributes:
      label: Deployment Environment
      description: Where is Zetian deployed?
      options:
        - Development Machine
        - On-Premise Server
        - Cloud VM (AWS/Azure/GCP)
        - Container (Docker/K8s)
        - Serverless Function
        - Other
    validations:
      required: true
  
  - type: input
    id: hardware
    attributes:
      label: Hardware Specifications
      description: CPU, RAM, and other relevant specs
      placeholder: "4 vCPUs, 8GB RAM, SSD storage"
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Zetian Version
      description: Which version of Zetian are you using?
      placeholder: "1.0.0"
    validations:
      required: true
  
  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: Which .NET version are you running on?
      placeholder: ".NET 8.0"
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which OS are you running on?
      options:
        - Windows Server 2022
        - Windows Server 2019
        - Windows 11
        - Windows 10
        - Linux (Ubuntu/Debian)
        - Linux (RHEL/CentOS)
        - Linux (Alpine)
        - macOS
        - Other
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this performance issue?
      placeholder: |
        1. Start server with configuration...
        2. Send X messages per second...
        3. Monitor resource usage...
    validations:
      required: false
  
  - type: textarea
    id: workarounds
    attributes:
      label: Attempted Workarounds
      description: Have you tried anything to improve performance?
      placeholder: |
        - Increased connection pool size
        - Adjusted buffer sizes
        - Modified configuration...
    validations:
      required: false
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Performance Checklist
      description: Please confirm you've checked these common issues
      options:
        - label: I'm using the latest version of Zetian
        - label: I've reviewed the performance tuning documentation
        - label: I've checked for obvious configuration issues
        - label: The issue is reproducible
        - label: I can provide performance metrics