name: Question / Help
description: Ask a question or request help with Zetian SMTP Server
title: "[Question]: "
labels: ["question", "help wanted"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Need help with Zetian? We're here to assist! Please check our [documentation](https://github.com/Taiizor/Zetian/wiki) and [discussions](https://github.com/Taiizor/Zetian/discussions) first.
  
  - type: dropdown
    id: question-type
    attributes:
      label: Question Category
      description: What type of help do you need?
      options:
        - How to use a specific feature
        - Configuration help
        - Authentication setup
        - Performance optimization
        - Integration with other systems
        - Troubleshooting
        - Best practices
        - Architecture guidance
        - Other
    validations:
      required: true
  
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know or what help do you need?
      placeholder: "How do I configure Zetian to...?"
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to achieve
      placeholder: |
        I'm building an application that...
        I need to send emails with...
        My use case requires...
    validations:
      required: false
  
  - type: textarea
    id: attempted-solutions
    attributes:
      label: What I've Tried
      description: Describe what you've already attempted
      placeholder: |
        I've tried configuring...
        I looked at the documentation for...
        I attempted to use...
    validations:
      required: false
  
  - type: textarea
    id: code-example
    attributes:
      label: Current Code (if applicable)
      description: Share your current implementation attempt
      placeholder: |
        ```csharp
        var server = new SmtpServer(config);
        // Your code here
        ```
      render: csharp
    validations:
      required: false
  
  - type: input
    id: version
    attributes:
      label: Zetian Version
      description: Which version of Zetian are you using?
      placeholder: "1.0.0"
    validations:
      required: false
  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details that might help us answer your question
      placeholder: "Environment details, related libraries, etc."
    validations:
      required: false
  
  - type: checkboxes
    id: search-confirmation
    attributes:
      label: Search Confirmation
      description: Please confirm you've searched for existing answers
      options:
        - label: I have searched the existing issues and discussions
        - label: I have checked the documentation
        - label: This question is specifically about Zetian, not general SMTP