name: Security Vulnerability
description: Report a security vulnerability in Zetian (for non-critical issues)
title: "[Security]: "
labels: ["security", "priority:high"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For critical security vulnerabilities, please DO NOT create a public issue. 
        Instead, email us directly at: taiizor@vegalya.com or use GitHub's Security Advisory feature.
        
        This form is for low to medium severity issues that can be disclosed publicly.
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low - Minor issue with minimal impact
        - Medium - Moderate impact, workaround available
        - High - Significant impact (consider private disclosure)
        - Critical - DO NOT USE THIS FORM - Email us instead
    validations:
      required: true
  
  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication Bypass
        - Authorization Issue
        - Input Validation
        - Injection Attack (Command, SMTP, etc.)
        - Denial of Service (DoS)
        - Information Disclosure
        - Session Management
        - Cryptography Weakness
        - Configuration Issue
        - Other
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: "The vulnerability allows an attacker to..."
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be exploited?
      placeholder: |
        1. Configure server with...
        2. Send malformed request...
        3. Observe unauthorized access...
    validations:
      required: true
  
  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Who is affected?
        - What data/functionality is at risk?
        - What are the potential consequences?
    validations:
      required: true
  
  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept (if applicable)
      description: Provide code or commands demonstrating the vulnerability
      placeholder: |
        ```csharp
        // PoC code here
        ```
      render: csharp
    validations:
      required: false
  
  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How can this vulnerability be fixed or mitigated?
      placeholder: "The issue can be resolved by..."
    validations:
      required: false
  
  - type: input
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions of Zetian are affected?
      placeholder: "All versions before 1.0.5"
    validations:
      required: true
  
  - type: checkboxes
    id: affected-components
    attributes:
      label: Affected Components
      description: Which components are affected by this vulnerability?
      options:
        - label: Authentication Module
        - label: Command Processing
        - label: Message Parser
        - label: Rate Limiter
        - label: TLS/SSL Implementation
        - label: Configuration System
        - label: Extension Handlers
        - label: Session Management
  
  - type: input
    id: cve
    attributes:
      label: CVE ID (if applicable)
      description: If a CVE has been assigned, provide it here
      placeholder: "CVE-2024-XXXXX"
    validations:
      required: false
  
  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant references, similar vulnerabilities, or documentation
      placeholder: |
        - OWASP: https://...
        - Similar issue in other SMTP servers...
    validations:
      required: false
  
  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm the following
      options:
        - label: I understand this is a public disclosure
          required: true
        - label: This is not a critical vulnerability requiring private disclosure
          required: true
        - label: I have followed responsible disclosure practices
          required: true
        - label: I agree to work with maintainers on a fix