<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <LangVersion>preview</LangVersion>
        <IsTestProject>true</IsTestProject>
        <AnalysisLevel>preview</AnalysisLevel>
        <ImplicitUsings>enable</ImplicitUsings>
        <TargetFramework>net11.0</TargetFramework>
        <RootNamespace>Zetian.HealthCheck.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Zetian.HealthCheck\Zetian.HealthCheck.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="xunit.v3" Version="4.0.0" />
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="8.10.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="11.0.0-preview.7.26381.103" />
    </ItemGroup>

</Project>