<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <LangVersion>preview</LangVersion>
        <AnalysisLevel>preview</AnalysisLevel>
        <ImplicitUsings>enable</ImplicitUsings>
        <TargetFramework>net11.0</TargetFramework>
        <RootNamespace>Zetian.Examples</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Zetian\Zetian.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="11.0.0-preview.7.26381.103" />
    </ItemGroup>

</Project>