name: .NET Desktop

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  Build:

    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [
            Release
        ]
        solution: [
            Zetian.sln,
        ]

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2.0.0

    # Execute all unit tests in the solution
    - name: Execute Unit Tests
      run: dotnet test ${{ matrix.solution }} -c ${{ matrix.configuration }} /nowarn:CS0067,CS0108,CS0109,CS0114,CS0169,CS0414,CS0649,CA1416,NU5104,NETSDK1138,SYSLIB0003
      env:
        NUGET_CONFIG_PATH: ./NuGet.Config

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the Zetian
      run: msbuild ${{ matrix.solution }} /t:Restore /p:Configuration=$env:Configuration
      env:
        NUGET_CONFIG_PATH: ./NuGet.Config
        Configuration: ${{ matrix.configuration }}